workspace:
  base: /drone
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  owncloud-download-v8orv9:
    image: owncloudci/php:7.0
    pull: true
    commands:
      - pwd
      - rm -rf owncloud
      - .drone/download.sh ${FROM} ${TO}
      - tar -jxf owncloud-${FROM}.tar.bz2 -C /drone/src
    when:
      matrix:
        MAJOR_VERSION: v8orv9

  owncloud-download-v10:
    image: owncloudci/php:7.2
    pull: true
    commands:
      - pwd
      - rm -rf owncloud
      - .drone/download.sh ${FROM} ${TO}
      - tar -jxf owncloud-${FROM}.tar.bz2 -C /drone/src
    when:
      matrix:
        MAJOR_VERSION: v10

  install-from-version-v8orv9:
    image: owncloudci/php:7.0
    pull: true
    environment:
      - DB_TYPE=${DB_TYPE}
    commands:
      - cd owncloud
      - ../.drone/install-server.sh
      - more config/config.php
      - php -f cron.php
      - php -f cron.php
      - php ./occ app:disable activity
      - php ./occ app:disable files_pdfviewer
      - php ./occ app:disable files_texteditor
      - php ./occ app:disable gallery
      - php ./occ app:disable files_videoplayer
      - php ./occ app:disable files_videoviewer
      - php ./occ app:disable updater
      - php ./occ app:disable templateeditor
    when:
      matrix:
        MAJOR_VERSION: v8orv9

  install-from-version-v10:
    image: owncloudci/php:7.1
    pull: true
    environment:
      - DB_TYPE=${DB_TYPE}
      - EXTRA_APPS_PATHS_DIR=${EXTRA_APPS_PATHS_DIR}
    commands:
      - cd owncloud
      - ../.drone/install-server.sh
      - more config/config.php
      - php -f cron.php
      - php -f cron.php
      - php ./occ app:disable activity
      - php ./occ app:disable files_pdfviewer
      - php ./occ app:disable files_texteditor
      - php ./occ app:disable gallery
      - php ./occ app:disable files_videoplayer
      - php ./occ app:disable files_videoviewer
      - php ./occ app:disable updater
      - php ./occ app:disable templateeditor
    when:
      matrix:
        MAJOR_VERSION: v10

  upgrade-test:
    image: owncloudci/php:7.2
    pull: true
    commands:
      - cd owncloud
      - cat version.php
      - ls | grep -v data | grep -v config | grep -v apps-external | xargs rm -rf
      - tar -jxf /drone/src/owncloud-${TO}.tar.bz2 -C /drone/src
      - cat version.php
      - php ./occ up

  run-phpunit:
    image: owncloudci/php:7.2
    pull: true
    commands:
      - cd owncloud
      - php ./occ app:disable gallery
      - chmod +x lib/composer/phpunit/phpunit/phpunit
      - cd tests
      - ../lib/composer/phpunit/phpunit/phpunit --configuration phpunit-autotest.xml --log-junit "autotest-results-$DATABASE.xml"

  notify-rocketchat:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      local: false
      status: [ changed, failure ]

services:
  mysql:
    image: ${MYSQL_IMAGE=mysql:5.5}
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  postgres:
    image: ${POSTGRES_IMAGE=postgres:9.4}
    environment:
      - POSTGRES_USER=owncloud
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=owncloud
    when:
      matrix:
        DB_TYPE: postgres

  oracle:
    image: owncloudci/oracle-xe
    when:
      matrix:
        DB_TYPE: oracle

matrix:
  include:
    - FROM: 10.3.0
      TO: daily-master-qa
      DB_TYPE: mysql
      MAJOR_VERSION: v10
      EXTRA_APPS_PATHS_DIR: apps-external
    - FROM: 10.4.0
      TO: daily-master-qa
      DB_TYPE: mysql
      MAJOR_VERSION: v10
      EXTRA_APPS_PATHS_DIR: apps-external
    - FROM: 10.6.0
      TO: daily-master-qa
      DB_TYPE: mysql
      MAJOR_VERSION: v10
      EXTRA_APPS_PATHS_DIR: apps-external
    - FROM: 10.7.0
      TO: daily-master-qa
      DB_TYPE: mysql
      MAJOR_VERSION: v10
      EXTRA_APPS_PATHS_DIR: apps-external

#   Needs to be adressed in core https://github.com/owncloud/core/issues/33187
#    - FROM: 8.2.11
#      TO: daily-master-qa
#      DB_TYPE: postgres
#      POSTGRES_IMAGE: postgres:10.3
#    - FROM: 8.2.11
#      TO: daily-master-qa
#      DB_TYPE: postgres
#      POSTGRES_IMAGE: postgres:10.4
#    - FROM: 8.2.11
#      TO: daily-master-qa
#      DB_TYPE: postgres
#      POSTGRES_IMAGE: postgres:11

