workspace:
  base: /drone
  path: src

branches:
  - master

clone:
  git:
    image: plugins/git:1
    pull: true

pipeline:
  owncloud-download:
    image: owncloudci/php:7.0
    pull: true
    commands:
      - pwd
      - rm -rf owncloud
      - .drone/download.sh ${FROM} ${TO}
      - tar -jxf owncloud-${FROM}.tar.bz2 -C /drone/src

  install-from-version:
    image: owncloudci/php:7.0
    pull: true
    environment:
      - DB_TYPE=${DB_TYPE}
    commands:
      - cd owncloud
      - ../.drone/install-server.sh
      - more config/config.pphp
      - php -f cron.php
      - php -f cron.php
      - php ./occ app:disable activity
      - php ./occ app:disable files_pdfviewer
      - php ./occ app:disable files_texteditor
      - php ./occ app:disable gallery
      - php ./occ app:disable files_videoplayer
      - php ./occ app:disable files_videoviewer
      - php ./occ app:disable updater

  upgrade-test:
    image: owncloudci/php:7.1
    pull: true
    commands:
      - cd owncloud
      - ls | grep -v data | grep -v config | xargs rm -rf
      - cd ..
      - tar -jxf owncloud-${TO}.tar.bz2 -C /drone/src
      - cd owncloud
      - php ./occ up

  notify-rocketchat:
    image: plugins/slack:1
    pull: true
    secrets: [ slack_webhook ]
    channel: builds
    when:
      local: false
      status: [ changed, failure ]

services:
  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_USER=owncloud
      - MYSQL_PASSWORD=owncloud
      - MYSQL_DATABASE=owncloud
      - MYSQL_ROOT_PASSWORD=owncloud
    when:
      matrix:
        DB_TYPE: mysql

  postgres:
    image: ${POSTGRES_IMAGE=postgres:9.4}
    environment:
      - POSTGRES_USER=owncloud
      - POSTGRES_PASSWORD=owncloud
      - POSTGRES_DB=owncloud
    when:
      matrix:
        DB_TYPE: postgres

  oracle:
    image: deepdiver/docker-oracle-xe-11g
    when:
      matrix:
        DB_TYPE: oracle


matrix:
  include:
    - FROM: 8.2.11
      TO: 10.0.8
      DB_TYPE: sqlite
    - FROM: 8.2.11
      TO: 10.0.8
      DB_TYPE: mysql
    - FROM: 8.2.11
      TO: 10.0.8
      DB_TYPE: postgres
    - FROM: 8.2.11
      TO: 10.0.8
      DB_TYPE: oracle
    - FROM: 9.0.9
      TO: 10.0.8
      DB_TYPE: sqlite
    - FROM: 9.0.9
      TO: 10.0.8
      DB_TYPE: mysql
    - FROM: 9.0.9
      TO: 10.0.8
      DB_TYPE: postgres
    - FROM: 9.0.9
      TO: 10.0.8
      DB_TYPE: oracle
    - FROM: 9.1.5
      TO: 10.0.8
      DB_TYPE: sqlite
    - FROM: 9.1.5
      TO: 10.0.8
      DB_TYPE: mysql
    - FROM: 9.1.5
      TO: 10.0.8
      DB_TYPE: postgres
    - FROM: 9.1.5
      TO: 10.0.8
      DB_TYPE: oracle
    - FROM: 10.0.4
      TO: 10.0.8
      DB_TYPE: sqlite
    - FROM: 10.0.4
      TO: 10.0.8
      DB_TYPE: mysql
    - FROM: 10.0.4
      TO: 10.0.8
      DB_TYPE: postgres
    - FROM: 10.0.4
      TO: 10.0.8
      DB_TYPE: oracle

    - FROM: 8.2.11
      TO: 10.0.9
      DB_TYPE: sqlite
    - FROM: 8.2.11
      TO: 10.0.9
      DB_TYPE: mysql
    - FROM: 8.2.11
      TO: 10.0.9
      DB_TYPE: postgres
    - FROM: 8.2.11
      TO: 10.0.9
      DB_TYPE: oracle
    - FROM: 9.0.9
      TO: 10.0.9
      DB_TYPE: sqlite
    - FROM: 9.0.9
      TO: 10.0.9
      DB_TYPE: mysql
    - FROM: 9.0.9
      TO: 10.0.9
      DB_TYPE: postgres
    - FROM: 9.0.9
      TO: 10.0.9
      DB_TYPE: oracle
    - FROM: 9.1.5
      TO: 10.0.9
      DB_TYPE: sqlite
    - FROM: 9.1.5
      TO: 10.0.9
      DB_TYPE: mysql
    - FROM: 9.1.5
      TO: 10.0.9
      DB_TYPE: postgres
    - FROM: 9.1.5
      TO: 10.0.9
      DB_TYPE: oracle
    - FROM: 10.0.4
      TO: 10.0.9
      DB_TYPE: sqlite
    - FROM: 10.0.4
      TO: 10.0.9
      DB_TYPE: mysql
    - FROM: 10.0.4
      TO: 10.0.9
      DB_TYPE: postgres
    - FROM: 10.0.4
      TO: 10.0.9
      DB_TYPE: oracle

    - FROM: 8.2.11
      TO: daily-stable10-qa
      DB_TYPE: sqlite
    - FROM: 8.2.11
      TO: daily-stable10-qa
      DB_TYPE: mysql
    - FROM: 8.2.11
      TO: daily-stable10-qa
      DB_TYPE: postgres
    - FROM: 8.2.11
      TO: daily-stable10-qa
      DB_TYPE: oracle
    - FROM: 9.0.9
      TO: daily-stable10-qa
      DB_TYPE: sqlite
    - FROM: 9.0.9
      TO: daily-stable10-qa
      DB_TYPE: mysql
    - FROM: 9.0.9
      TO: daily-stable10-qa
      DB_TYPE: postgres
    - FROM: 9.0.9
      TO: daily-stable10-qa
      DB_TYPE: oracle
    - FROM: 9.1.5
      TO: daily-stable10-qa
      DB_TYPE: sqlite
    - FROM: 9.1.5
      TO: daily-stable10-qa
      DB_TYPE: mysql
    - FROM: 9.1.5
      TO: daily-stable10-qa
      DB_TYPE: postgres
    - FROM: 9.1.5
      TO: daily-stable10-qa
      DB_TYPE: oracle
    - FROM: 10.0.4
      TO: daily-stable10-qa
      DB_TYPE: sqlite
    - FROM: 10.0.4
      TO: daily-stable10-qa
      DB_TYPE: mysql
    - FROM: 10.0.4
      TO: daily-stable10-qa
      DB_TYPE: postgres
    - FROM: 10.0.4
      TO: daily-stable10-qa
      DB_TYPE: oracle

    
